require 'rubygems'

require "bundler"
Bundler.require(:default)

require 'lib/blackout'
require 'rspec/core/rake_task'

desc "Run all spec"
RSpec::Core::RakeTask.new do |t|
  t.pattern = 'spec/**/*_spec.rb'
end

# import data from excel file
task :import do
  blackout_data = Blackout::Utils.blackout_data
  File.open("output/blackout.json", 'w') {|f| f.write(blackout_data.to_json) }
end